
sudo: required
services:
    - docker


before_install:
    - docker build -t sandricionut/docker-react -f Dockerfile.dev .


script:
    # - docker run sandricionut/docker-react npm run test -- --coverage
    - docker run -e CI=true sandricionut/docker-react npm run test

language: generic